
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Iraildo55882056
 */
public class TelaNodelay extends javax.swing.JInternalFrame {

    /**
     * 
     * 
     * Creates new form TelaNodelay
     */
    
    double valores;
    String gastoGanho;
    double totalValores;
    
    public TelaNodelay() {
        initComponents();
        informacoesImportantes();
        
        
    }
    
    public void informacoesImportantes () {
    
        caixaResultado.setEnabled(false);
        
        reset();
        
    }

    
    public void reset() {
    
        caixaDescricao.setText(null);
        caixaValor.setText(null);
        botaoGasto.clearSelection();
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoGasto = new javax.swing.ButtonGroup();
        radioGanho = new javax.swing.JRadioButton();
        radioGasto = new javax.swing.JRadioButton();
        caixaDescricao = new javax.swing.JTextField();
        caixaValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        botaoLancamento = new javax.swing.JButton();
        caixaResultado = new javax.swing.JTextField();
        R$ = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        botaoGasto.add(radioGanho);
        radioGanho.setText("Ganho");

        botaoGasto.add(radioGasto);
        radioGasto.setText("Gasto");

        jLabel1.setText("Descrição:");

        jLabel2.setText("R$");

        jLabel3.setText("Valor:");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Ganho / Gasto", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        botaoLancamento.setText("Fazer lançamento");
        botaoLancamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLancamentoMouseClicked(evt);
            }
        });

        R$.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioGanho)
                            .addComponent(radioGasto))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(825, 825, 825)
                .addComponent(R$)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoLancamento, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(caixaResultado))
                .addContainerGap(848, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioGanho)
                    .addComponent(caixaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioGasto)
                    .addComponent(caixaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R$))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLancamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLancamentoMouseClicked
        
        
        if (caixaDescricao.getText().isBlank() || caixaValor.getText().isBlank()){
        
            JOptionPane.showMessageDialog(null,"Preencha todos os campos!");
            
            reset();
            
            return;
            
        }
        
        if(radioGasto.isSelected() == false && radioGanho.isSelected() == false) {
            
                JOptionPane.showMessageDialog(null,"Preencha todos os campos!");
                
                reset();
                
                return;
            }
            
           // radioGanho.isSelected() == false
           
        
        double valores = Double.parseDouble(caixaValor.getText());
      
        if (radioGanho.isSelected() == true) {
        
            gastoGanho = "Ganho";
            totalValores = totalValores + valores;
        }
        
        else {
        
            gastoGanho = "Gasto";
            totalValores = totalValores - valores;
        
        }
            
            
        
         DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();

         Object [] dados = {caixaDescricao.getText(), caixaValor.getText(), gastoGanho};

         tabelaModelo.addRow(dados);
         
         caixaResultado.setText(String.valueOf(totalValores));
        
         reset();
        
    }//GEN-LAST:event_botaoLancamentoMouseClicked

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel R$;
    private javax.swing.ButtonGroup botaoGasto;
    private javax.swing.JButton botaoLancamento;
    private javax.swing.JTextField caixaDescricao;
    private javax.swing.JTextField caixaResultado;
    private javax.swing.JTextField caixaValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioGanho;
    private javax.swing.JRadioButton radioGasto;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
