/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicio08_bancodedados;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Iraildo55882056
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        menuBar.setVisible(false);
        setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JDesktopPane();
        labelUsuario = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        caixaSenha = new javax.swing.JPasswordField();
        caixaUsuario = new javax.swing.JTextField();
        botaoEntrar = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemEditarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuDeslogar = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelUsuario.setText("Usuário:");

        labelSenha.setText("Senha:");

        botaoEntrar.setText("Entrar");
        botaoEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEntrarMouseClicked(evt);
            }
        });

        painelPrincipal.setLayer(labelUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelPrincipal.setLayer(labelSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelPrincipal.setLayer(caixaSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelPrincipal.setLayer(caixaUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelPrincipal.setLayer(botaoEntrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSenha)
                            .addComponent(labelUsuario))
                        .addGap(29, 29, 29)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(caixaUsuario)
                            .addComponent(caixaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(666, 666, 666)
                        .addComponent(botaoEntrar)))
                .addContainerGap(1012, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(caixaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenha)
                    .addComponent(caixaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(botaoEntrar)
                .addContainerGap(639, Short.MAX_VALUE))
        );

        jMenu1.setText("Controle de Usuário");

        itemEditarUsuario.setText("Editar Usuários");
        itemEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(itemEditarUsuario);

        menuBar.add(jMenu1);

        jMenu2.setText("Cadastro");
        menuBar.add(jMenu2);

        menuDeslogar.setText("Deslogar");
        menuDeslogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDeslogarMouseClicked(evt);
            }
        });
        menuBar.add(menuDeslogar);

        jMenu4.setText("Sair");
        menuBar.add(jMenu4);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEntrarMouseClicked
        
        try {
        
            Connection connection = IntegracaoBanco.conexaoBanco();
            
            String sql = "SELECT * FROM login WHERE usuario = ? "
            + "AND senha = UPPER(MD5(?)) AND situacao = 'A' ;";
            
            PreparedStatement stmt = connection.prepareStatement(sql);
            
            stmt.setString(1, caixaUsuario.getText());
            stmt.setString(2, caixaSenha.getText());
            ResultSet resultSet = stmt.executeQuery();
            
            if(resultSet.next()){
            
                menuBar.setVisible(true);
                labelSenha.setVisible(false);
                labelUsuario.setVisible(false);
                botaoEntrar.setVisible(false);
                caixaSenha.setVisible(false);
                caixaUsuario.setVisible(false);
                caixaUsuario.setText(null);
                caixaSenha.setText(null);
            }
            
            else {
            
                JOptionPane.showMessageDialog(null, "Login incorreto!");
            
            }
            
        } catch (SQLException ex) {
   
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        
    }//GEN-LAST:event_botaoEntrarMouseClicked

    private void menuDeslogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDeslogarMouseClicked
        
        menuBar.setVisible(false);
        labelSenha.setVisible(true);
        labelUsuario.setVisible(true);
        botaoEntrar.setVisible(true);
        caixaSenha.setVisible(true);
        caixaUsuario.setVisible(true);
        
    }//GEN-LAST:event_menuDeslogarMouseClicked

    private void itemEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarUsuarioActionPerformed
        
        TelaEditarUsuario telaEditarUsuario = new TelaEditarUsuario();
        painelPrincipal.add(telaEditarUsuario);
        telaEditarUsuario.setVisible(true);
        
        
    }//GEN-LAST:event_itemEditarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JPasswordField caixaSenha;
    private javax.swing.JTextField caixaUsuario;
    private javax.swing.JMenuItem itemEditarUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuDeslogar;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
