/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicio05_raquete;

import javax.swing.JOptionPane;

/**
 * 
 * 
 * Utilizando a mesma logica do exercício da Aeronave :
Cria uma interface que :

Carregar Raquete.
Usar a Raquete.
Ligar Raquete

Só pode usar a raquete se ela tiver carregada e se ela estiver ligada.
Ao carregar a raquete, setar o valor para 100.
Cada uso da raquete, ela perde 10% da carga.
Ao final da carga, a raquete desliga.


Então as condições para usar ela são:

Verificar se a raquete está carregada
Verificar se está ligada.


Usar o TextArea, Jbutton e o TextField.
 * 
 *
 * @author Iraildo55882056
 */
public class Raquete extends javax.swing.JFrame {

    /**
     * Creates new form Raquete
     */
    
    int carregar = 0;
    
    public Raquete() {
        initComponents();
        
        metodoRepetir();
        
        
    }
    
    public void metodoReset() {
    
        mostraLigar.setText("Desligado");
        mostraUsar.setText(String.valueOf(carregar) + "%");
        mostraCarregar.setText("Descarregado");
        nivelBateria.setText("…");
    
    }
    
    
    public void metodoRepetir() {
    
        mostraLigar.setEnabled(false);
        mostraUsar.setEnabled(false);
        mostraCarregar.setEnabled(false);
        mostraTotal.setEnabled(false);
        nivelBateria.setEnabled(false);
        
        mostraLigar.setText("Desligado");
        mostraUsar.setText(String.valueOf(carregar) + "%");
        mostraCarregar.setText("Descarregado");
        nivelBateria.setText("…");
    
        metodoBateria();
        mostraTotal();
        metodoReset();
        
    }
    
    
    public void metodoBateria() {
        
        
        if (mostraLigar.getText().equals("Desligado") && carregar == 0) {
        
            nivelBateria.setText("…");
        
        }
        
        if (mostraLigar.getText().equals("Ligado") && carregar == 0) {
        
            nivelBateria.setText("…");
        
        }
        
        if (mostraLigar.getText().equals("Ligado") && carregar == 10) {
        
            nivelBateria.setText("▁");
        
        }
    
        if (mostraLigar.getText().equals("Ligado") && carregar == 20) {
        
            nivelBateria.setText("▁▂");
        
        }
        
        if (mostraLigar.getText().equals("Ligado") && carregar == 30) {
        
            nivelBateria.setText("▁▂▃");
        
        }
        
        if (mostraLigar.getText().equals("Ligado") && carregar == 40) {
        
            nivelBateria.setText("▁▂▃▄");
        
        }
        
        if (mostraLigar.getText().equals("Ligado") && carregar == 50) {
        
            nivelBateria.setText("▁▂▃▄▅");
        
        }
        
        if (mostraLigar.getText().equals("Ligado") && carregar == 60) {
        
            nivelBateria.setText("▁▂▃▄▅▆");
        
        }
    
        if (mostraLigar.getText().equals("Ligado") && carregar == 70) {
        
            nivelBateria.setText("▁▂▃▄▅▆▇");
        
        }
        
        if (mostraLigar.getText().equals("Ligado") && carregar == 80) {
        
            nivelBateria.setText("▁▂▃▄▅▆▇█");
        
        }
        
        if (mostraLigar.getText().equals("Ligado") && carregar == 90) {
        
            nivelBateria.setText("▁▂▃▄▅▆▇██");
        
        }
        
        if (mostraLigar.getText().equals("Ligado") && carregar == 100) {
        
            nivelBateria.setText("▁▂▃▄▅▆▇███");
        
        }
        
    }
    
    public void mostraTotal() {
        
        
        mostraTotal.setText("Raquete: " + mostraLigar.getText() + 
        "\n" + mostraUsar.getText() +
        "\nNível da bateria: " + mostraCarregar.getText() +
        "\n");
        metodoBateria();
        
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mostraTotal = new javax.swing.JTextArea();
        label = new javax.swing.JLabel();
        botaoUsarRaquete = new javax.swing.JButton();
        botaoCarregarRaquete = new javax.swing.JButton();
        botaoLigarRaquete = new javax.swing.JButton();
        mostraUsar = new javax.swing.JTextField();
        mostraCarregar = new javax.swing.JTextField();
        mostraLigar = new javax.swing.JTextField();
        nivelBateria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mostraTotal.setColumns(20);
        mostraTotal.setRows(5);
        jScrollPane1.setViewportView(mostraTotal);

        label.setText("Mate o Mosquito");

        botaoUsarRaquete.setText("Usar Raquete 🎾");
        botaoUsarRaquete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoUsarRaqueteMouseClicked(evt);
            }
        });

        botaoCarregarRaquete.setText("Carregar Raquete 🔋");
        botaoCarregarRaquete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCarregarRaqueteMouseClicked(evt);
            }
        });

        botaoLigarRaquete.setText("Ligar Raquete ▶︎");
        botaoLigarRaquete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLigarRaqueteMouseClicked(evt);
            }
        });

        nivelBateria.setText("   Nível da bateria 🔋");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botaoUsarRaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(mostraUsar))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botaoCarregarRaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(mostraCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botaoLigarRaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(mostraLigar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(nivelBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoLigarRaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mostraLigar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoUsarRaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mostraUsar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoCarregarRaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mostraCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addComponent(nivelBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
   
    
    
    private void botaoLigarRaqueteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLigarRaqueteMouseClicked
        
        if (mostraLigar.getText().equals("Desligado")) {
        
            mostraLigar.setText("Ligado");
            
            mostraTotal();
            
        }
        
    }//GEN-LAST:event_botaoLigarRaqueteMouseClicked

    private void botaoUsarRaqueteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoUsarRaqueteMouseClicked
        
        if (mostraLigar.getText().equals("Ligado") && carregar > 0) {
            
            carregar = carregar - 10;
            
            mostraUsar.setText(String.valueOf(carregar) + "%");
            
            mostraTotal();
        
        }
        
        if (mostraLigar.getText().equals("Ligado") && carregar == 0) {
        
            carregar = 0;
            
            mostraTotal();
            JOptionPane.showMessageDialog(null, "Sua bateria está descarregada!");
            metodoReset();
        }
        
 
       if (carregar < 100 && carregar > 0 && mostraCarregar.getText().equals("Carregado")) {
        
            mostraCarregar.setText("Descarregando");
                mostraTotal();
        
        }
 
    }//GEN-LAST:event_botaoUsarRaqueteMouseClicked

    private void botaoCarregarRaqueteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCarregarRaqueteMouseClicked
        
        if (carregar >= 0) {
            
            carregar = 100;

            mostraUsar.setText(String.valueOf(carregar));

            JOptionPane.showMessageDialog(null, "Sua bateria está 100% carregada!");
            
            mostraCarregar.setText("Carregado");
            
            mostraTotal();
            
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_botaoCarregarRaqueteMouseClicked


        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Raquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Raquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Raquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Raquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Raquete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCarregarRaquete;
    private javax.swing.JButton botaoLigarRaquete;
    private javax.swing.JButton botaoUsarRaquete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTextField mostraCarregar;
    private javax.swing.JTextField mostraLigar;
    private javax.swing.JTextArea mostraTotal;
    private javax.swing.JTextField mostraUsar;
    private javax.swing.JTextField nivelBateria;
    // End of variables declaration//GEN-END:variables
}
